### ISSUE TITLE
I get tons of errors, i need a little bit of help, all errors are in the backends cpp file

### ISSUE THREAD

**Issue by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [ahmed605/imgui-uwp#2]
![image](https://github.com/ahmed605/imgui-uwp/assets/126031366/95fa226e-411e-4580-b012-ff11a5b2ce35)
this is the error i get, can you please help me <3

**Comment by ChairWareDev** [comment]
ignore everythign before, i was being an idiot
this is the true error

![image](https://github.com/ahmed605/imgui-uwp/assets/126031366/e679d505-0ef1-4b85-ac47-47110154f5e0)

**Comment by ahmed605** [comment]
which ImGui version are you using? ImGui-UWP was only tested on v1.90+
also what are the C++ & Windows SDK versions used? ImGui-UWP was only tested on C++ 17 with Windows 11 22000+ SDK

also make sure you included ImGui headers in this order: `imgui.h`, `imgui_impl_uwp.h`, and the graphics backend header of choice, so like this for example:
```cpp
#include <imgui.h>
#include <imgui_impl_uwp.h>
#include <imgui_impl_dx12.h>
```

**Comment by ChairWareDev** [comment]
> which ImGui version are you using? ImGui-UWP was only tested on v1.90+ also what are the C++ & Windows SDK versions used? ImGui-UWP was only tested on C++ 17 with Windows 11 22000+ SDK
> 
> also make sure you included ImGui headers in this order: `imgui.h`, `imgui_impl_uwp.h`, and the graphics backend header of choice, so like this for example:
> 
> ```c++
> #include <imgui.h>
> #include <imgui_impl_uwp.h>
> #include <imgui_impl_dx12.h>
> ```

I’m on imgui 1.90, C++20, and windows 10 pro

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
ok, i got everything narrowed down to just these issues.

![image](https://github.com/ahmed605/imgui-uwp/assets/126031366/413c7b1b-d462-4c83-bfd6-d5a95bba3ac3)

i tried using GPT but it was no help

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
im using imgui 1.95, C++ 20, release x64

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
ive also tried to set them to values but nothing worked

**Comment by ahmed605** [comment]
> ok, i got everything narrowed down to just these issues.
> 
> ![image](https://private-user-images.githubusercontent.com/126031366/316315530-413c7b1b-d462-4c83-bfd6-d5a95bba3ac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDE0NTAsIm5iZiI6MTcxMTMwMTE1MCwicGF0aCI6Ii8xMjYwMzEzNjYvMzE2MzE1NTMwLTQxM2M3YjFiLWQ0NjItNGM4My1iZmQ2LWQ1YTk1YmJhM2FjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxNzI1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzc3ZjY1MWViYjdkM2ZlNzBhZjYwMGIzMTc5OTc5Njk0MDMxZmJjZTg4ZWU1N2NhOWUwYjIzOGMxZDRhZGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ozr78PYFFRp7bJ2PCg4wGgUWelj5aehtjZLNTNNnVM8)
> 
> i tried using GPT but it was no help

Seems like you aren't using a standard UWP project, can you check if linking `WindowsApp.lib` fixes it?

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
> > ok, i got everything narrowed down to just these issues.
> > ![image](https://private-user-images.githubusercontent.com/126031366/316315530-413c7b1b-d462-4c83-bfd6-d5a95bba3ac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDE0NTAsIm5iZiI6MTcxMTMwMTE1MCwicGF0aCI6Ii8xMjYwMzEzNjYvMzE2MzE1NTMwLTQxM2M3YjFiLWQ0NjItNGM4My1iZmQ2LWQ1YTk1YmJhM2FjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxNzI1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzc3ZjY1MWViYjdkM2ZlNzBhZjYwMGIzMTc5OTc5Njk0MDMxZmJjZTg4ZWU1N2NhOWUwYjIzOGMxZDRhZGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ozr78PYFFRp7bJ2PCg4wGgUWelj5aehtjZLNTNNnVM8)
> > i tried using GPT but it was no help
> 
> Seems like you aren't using a standard UWP project, can you check if linking `WindowsApp.lib` fixes it?

i will try right now

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
IT FIXED IT!!! THANK YOU SO MUCH

Also, how can i hook keyboard inputs? i managed to do mouse inputs but not keyboard

**Comment by ahmed605** [comment]
the backend should already support keyboard input, I have tried it with built-in ImGui text input controls and it was working

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
![image](https://github.com/ahmed605/imgui-uwp/assets/126031366/bb5c43e7-89af-4d7b-9cc3-6a8f8506bc59)
i cant type still, is there something i need to add into my main code for it to work? currently i have only included the backends

**Comment by ahmed605** [comment]
Can you show me how do you initialize the backend?

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
thats what im having trouble with, im very new to imgui

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
this is my main thread

![image](https://github.com/ahmed605/imgui-uwp/assets/126031366/9cddb503-30a4-45f7-a780-67229456c188)

this is my current render init

![image](https://github.com/ahmed605/imgui-uwp/assets/126031366/a7d0fbef-73f2-465d-9258-01ad407cdff1)

**Comment by ahmed605** [comment]
oh this is how the backend should be initialized
https://github.com/ahmed605/imgui-uwp/blob/6e131e8de2d13f1824b2e0f32d3382f4c69ec4cd/examples/example_uwp_directx12/main.cpp#L76-L103

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
ill give it a shot, thanks!

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
do you have discord by any chance?

**Comment by ahmed605** [comment]
yes, `@ahmedwalid`

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
sent im havic

**Comment by qwepotiuwyasjlkdsajdghmnbxzcvgergergsdz** [comment]
![image](https://github.com/ahmed605/imgui-uwp/assets/126031366/ac584d7e-84e1-4bc8-b972-0989dcaad775)
